version: 1.0.{build}
image: Previous Visual Studio 2017
configuration: Release
platform:
  - Win32
  - x64
install:
  - cmd: git submodule update --init --recursive
build:
  project: asmjit.sln
  verbosity: minimal